# Generated by Django 4.2.18 on 2025-01-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VegistApp', '0002_category_product_review_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='getFilename'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='getFilename'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='getFilename'),
        ),
    ]
