# Generated by Django 4.2.18 on 2025-01-23 06:54

import VegistApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VegistApp', '0003_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=VegistApp.models.getFilename),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=VegistApp.models.getFilename),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=VegistApp.models.getFilename),
        ),
    ]
