# Generated by Django 4.2.18 on 2025-01-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VegistApp', '0007_order_orderitem_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
