# Generated by Django 4.2.18 on 2025-01-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VegistApp', '0010_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
