# Generated by Django 4.2.18 on 2025-01-29 05:00

import VegistApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VegistApp', '0012_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=VegistApp.models.get_current_time),
        ),
    ]
