# Generated by Django 4.2.18 on 2025-01-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VegistApp', '0019_alter_orderitem_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, null=True),
        ),
    ]
