# Generated by Django 4.2.18 on 2025-02-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VegistApp', '0030_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
