# Generated by Django 4.2.18 on 2025-02-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VegistApp', '0031_subscribers_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribers',
            old_name='status',
            new_name='subscribed',
        ),
    ]
