# Generated by Django 4.2.18 on 2025-02-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VegistApp', '0032_rename_status_subscribers_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='subscriber_email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
